// Hardcoded Uzbek UI strings for the notes feature (repo convention — no i18n lib).
export const NOTES_TEXT = {
  tabTitle: "Eslatmalarim",
  add: "Eslatma qo'shish",
  save: "Saqlash",
  cancel: "Bekor qilish",
  edit: "Tahrirlash",
  delete: "O'chirish",
  deleteConfirm: "Eslatma o'chirilsinmi?",
  done: "Tayyor",
  empty: "Hozircha eslatma yo'q. Birinchi eslatmangizni qo'shing.",
  emptyCourse: "Bu kurs bo'yicha hali eslatma yo'q.",
  emptySearch: "So'rovingiz bo'yicha eslatma topilmadi.",
  linkTimestamp: (t: string) => `${t} vaqtga bog'lash`,
  searchPlaceholder: "Eslatmalardan qidirish...",
  sortLabel: "Tartiblash",
  sortTimestamp: "Vaqt bo'yicha",
  sortRecent: "Avval yangi",
  export: "Markdown'ga eksport",
  saved: "Eslatma saqlandi",
  saveError: "Saqlashda xatolik. Qayta urinib ko'ring.",
  deleted: "Eslatma o'chirildi",
  autoSaved: "Saqlandi",
  placeholder: "Eslatma matnini kiriting...",
  loadError: "Eslatmalarni yuklab bo'lmadi.",
  goToLesson: "Darsga o'tish",
  toolbarBold: "Qalin",
  toolbarItalic: "Kursiv",
  toolbarBullet: "Ro'yxat",
  toolbarOrdered: "Raqamli ro'yxat",
  toolbarLink: "Havola",
  linkPrompt: "Havola manzilini kiriting:",
} as const;
